In [6]:
import oracledb
import pandas as pd
import numpy as np
import time
from datetime import datetime, timedelta
from sqlalchemy import create_engine, text
import importlib

import funciones_carga as funciones_carga
import funciones_recocido as funciones_recocido
#import restricciones as restricciones
#importlib.reload(funciones_carga)
#importlib.reload(funciones_recocido)
importlib.reload(funciones)
importlib.reload(funciones_carga)

In [7]:
try:
    matriz_distancias = funciones_carga.cargar_datos_distancias()
    tareas_recogida = funciones_carga.cargar_alumnos()    
    #funciones_carga.visualizar_diccionario_generico(matriz_distancias, n=5)    
    #funciones_carga.visualizar_diccionario_generico(tareas_recogida, n=5)    
    print("\n🔥 ¡Datos listos!")
except Exception as e:
    print(f"❌ Error al cargar datos: {e}")

✅ Matriz cargada: 4761 registros
✅ Cargadas 95 tareas de recogida independientes.

🔥 ¡Datos listos!

In [8]:
# Hallar Solución Inicial
tareas_recogida2 = pd.DataFrame(tareas_recogida)
tareas_recogida_div = (funciones_recocido.dividir_tareas_exceso_capacidad(tareas_recogida2))

# SOLUCIÓN INICIAL
solucion_inicial = funciones_recocido.construir_solucion_inicial(tareas_recogida_div,matriz_distancias)

# MOSTRAR
funciones_recocido.mostrar_solucion_inicial(solucion_inicial,tareas_recogida_div, matriz_distancias)

==========================================================================================
RESUMEN SOLUCIÓN INICIAL
==========================================================================================
    RUTA      CENTRO  NUM_PARADAS  ALUMNOS  BUS  OCUPACION_%  TIEMPO_MIN  \
0      1  C-18006728            1        1   38         2.63           5
1      2  C-18007022            2       49   55        89.09          25
2      3  C-18007022            6       55   55       100.00          59
3      4  C-18007022            5       25   38        65.79          65
4      5  C-18007034            6       40   55        72.73          24
5      6  C-18007046            5       18   38        47.37          84
6      7  C-18007058            4       51   55        92.73          38
7      8  C-18007083            4       44   55        80.00          89
8      9  C-18007083            5       11   38        28.95          68
9     10  C-18009353            3       19   38        50.00          56
10    11  C-18009353            3       11   38        28.95          52
11    12  C-18009353            7       14   38        36.84          82
12    13  C-18009353            5        5   38        13.16          85
13    14  C-18009353            3        3   38         7.89          81
14    15  C-18009353            5        5   38        13.16          66
15    16  C-18009353            3        3   38         7.89          41
16    17  C-18009481            1        1   38         2.63          10
17    18  C-18009717            1        2   38         5.26           8
18    19  C-18700049            1       55   55       100.00          21
19    20  C-18700049            2       13   38        34.21          54
20    21  C-18700323            1       55   55       100.00          10
21    22  C-18700323            1       55   55       100.00          12
22    23  C-18700323            1       45   55        81.82          10
23    24  C-18700323            1       44   55        80.00           6
24    25  C-18700323            2       47   55        85.45          37
25    26  C-18700323            6       48   55        87.27          74
26    27  C-18700426            1       43   55        78.18           4
27    28  C-18700426            4       55   55       100.00          20
28    29  C-18700426            6       15   38        39.47          88
29    30  C-18700426            3        4   38        10.53          53

    DISTANCIA_KM  COSTE_€
0           2.90    96.14
1          12.40   119.86
2          44.93   119.86
3          48.66   124.98
4          14.33   119.86
5          76.68   124.98
6          22.70   119.86
7          96.03   155.82
8          53.40   124.98
9          50.48    96.14
10         49.54    96.14
11         74.79   124.98
12         89.02   124.98
13         89.93   124.98
14         44.01   124.98
15         34.77    96.14
16          5.25    96.14
17          4.19    96.14
18         13.66   119.86
19         58.92    96.14
20         11.26   119.86
21         12.44   119.86
22         11.26   119.86
23          4.97   119.86
24         37.11   119.86
25         45.38   155.82
26          1.93   119.86
27         11.94   119.86
28         83.44   124.98
29         42.60    96.14

==========================================================================================
MÉTRICAS GLOBALES
==========================================================================================
TOTAL_RUTAS                   : 30
TOTAL_ALUMNOS                 : 836
TOTAL_PARADAS                 : 98
TIEMPO_TOTAL_MIN              : 1327
TIEMPO_MEDIO_RUTA             : 44.23
DISTANCIA_TOTAL_KM            : 1148.92
DISTANCIA_MEDIA_RUTA          : 38.3
COSTE_TOTAL_€                 : 3518.92
COSTE_MEDIO_RUTA              : 117.3
OCUPACION_MEDIA_%             : 54.73
RUTAS_BUS_38                  : 16
RUTAS_BUS_55                  : 14

==========================================================================================
VALIDACIÓN
==========================================================================================
✅ SOLUCIÓN VÁLIDA

,RUTA,CENTRO,NUM_PARADAS,ALUMNOS,BUS,OCUPACION_%,TIEMPO_MIN,DISTANCIA_KM,COSTE_€
0,1,C-18006728,1,1,38,2.63,5,2.90,96.14
1,2,C-18007022,2,49,55,89.09,25,12.40,119.86
2,3,C-18007022,6,55,55,100.00,59,44.93,119.86
3,4,C-18007022,5,25,38,65.79,65,48.66,124.98
4,5,C-18007034,6,40,55,72.73,24,14.33,119.86
5,6,C-18007046,5,18,38,47.37,84,76.68,124.98
6,7,C-18007058,4,51,55,92.73,38,22.70,119.86
7,8,C-18007083,4,44,55,80.00,89,96.03,155.82
8,9,C-18007083,5,11,38,28.95,68,53.40,124.98
9,10,C-18009353,3,19,38,50.00,56,50.48,96.14
10,11,C-18009353,3,11,38,28.95,52,49.54,96.14
11,12,C-18009353,7,14,38,36.84,82,74.79,124.98
12,13,C-18009353,5,5,38,13.16,85,89.02,124.98
13,14,C-18009353,3,3,38,7.89,81,89.93,124.98
14,15,C-18009353,5,5,38,13.16,66,44.01,124.98
15,16,C-18009353,3,3,38,7.89,41,34.77,96.14
16,17,C-18009481,1,1,38,2.63,10,5.25,96.14
17,18,C-18009717,1,2,38,5.26,8,4.19,96.14
18,19,C-18700049,1,55,55,100.00,21,13.66,119.86
19,20,C-18700049,2,13,38,34.21,54,58.92,96.14
20,21,C-18700323,1,55,55,100.00,10,11.26,119.86
21,22,C-18700323,1,55,55,100.00,12,12.44,119.86
22,23,C-18700323,1,45,55,81.82,10,11.26,119.86
23,24,C-18700323,1,44,55,80.00,6,4.97,119.86
24,25,C-18700323,2,47,55,85.45,37,37.11,119.86
25,26,C-18700323,6,48,55,87.27,74,45.38,155.82
26,27,C-18700426,1,43,55,78.18,4,1.93,119.86
27,28,C-18700426,4,55,55,100.00,20,11.94,119.86
28,29,C-18700426,6,15,38,39.47,88,83.44,124.98
29,30,C-18700426,3,4,38,10.53,53,42.60,96.14

In [9]:
# ==========================================================
# EXPORTAR SOLUCIÓN INICIAL A EXCEL MULTIHOJA
# ==========================================================

import pandas as pd

# ==========================================================
# LISTA DETALLE
# ==========================================================

datos_detalle = []

# ==========================================================
# LISTA RESUMEN
# ==========================================================

datos_resumen = []

# ==========================================================
# RECORRER RUTAS
# ==========================================================

for ruta in solucion_inicial:

    # ------------------------------------------------------
    # DATOS GENERALES RUTA
    # ------------------------------------------------------

    ruta_id = ruta["id"]

    centro = ruta["centro"]

    alumnos_ruta = ruta["alumnos"]

    bus = ruta["bus"]

    ocupacion = ruta["ocupacion"]

    tiempo = ruta["tiempo"]

    distancia = ruta["distancia"]

    coste = ruta["coste"]

    num_paradas = len(
        ruta["paradas"]
    )

    # ======================================================
    # RESUMEN
    # ======================================================

    datos_resumen.append({

        "RUTA": ruta_id,

        "CENTRO": centro,

        "NUM_PARADAS": num_paradas,

        "ALUMNOS_RUTA": alumnos_ruta,

        "BUS": bus,

        "OCUPACION_%": ocupacion,

        "TIEMPO_MIN": tiempo,

        "DISTANCIA_KM": distancia,

        "COSTE_€": coste
    })

    # ======================================================
    # DETALLE PARADAS
    # ======================================================

    for orden, parada in enumerate(

        ruta["paradas"],

        start=1
    ):

        datos_detalle.append({

            "RUTA": ruta_id,

            "CENTRO": centro,

            "ORDEN": orden,

            "PARADA": parada["parada"],

            "ALUMNOS_PARADA": parada["alumnos"],

            "ALUMNOS_RUTA": alumnos_ruta,

            "BUS": bus,

            "OCUPACION_%": ocupacion,

            "TIEMPO_MIN": tiempo,

            "DISTANCIA_KM": distancia,

            "COSTE_€": coste
        })

# ==========================================================
# DATAFRAMES
# ==========================================================

df_resumen = pd.DataFrame(
    datos_resumen
)

df_detalle = pd.DataFrame(
    datos_detalle
)

# ==========================================================
# EXPORTAR EXCEL MULTIHOJA
# ==========================================================

nombre_fichero = "solucion_inicial.xlsx"

with pd.ExcelWriter(

    nombre_fichero,

    engine="openpyxl"

) as writer:

    # ------------------------------------------------------
    # HOJA RESUMEN
    # ------------------------------------------------------

    df_resumen.to_excel(

        writer,

        sheet_name="Resumen_Rutas",

        index=False
    )

    # ------------------------------------------------------
    # HOJA DETALLE
    # ------------------------------------------------------

    df_detalle.to_excel(

        writer,

        sheet_name="Detalle_Rutas",

        index=False
    )

# ==========================================================
# MENSAJE
# ==========================================================

print(
    f"Excel exportado correctamente: {nombre_fichero}"
)

Excel exportado correctamente: solucion_inicial.xlsx

In [10]:
import itertools
import time
import pandas as pd

# ============================================================
# GENERAR COMBINACIONES DE PARÁMETROS
# ============================================================

def generar_configuraciones_sa():
    """
    Genera configuraciones típicas
    para experimentar con recocido simulado.

    Retorna
    -------
    DataFrame
    """

    # ========================================================
    # ESPACIO PARÁMETROS
    # ========================================================

    temperaturas = [100]

    factores_enfriamiento = [0.90,0.95,0.97]
    factores_enfriamiento = [0.95]

    iteraciones = [75, 90, 100, 110, 125]

    # Parametriza coste
    iteraciones = [75]
    pesos_coste = [1]
    pesos_rutas = [25, 30]
    pesos_ocupacion = [10]        
    pesos_distancia = [0.25, 0.1]

    # Parametriza distancia
    iteraciones = [75]
    pesos_coste = [1]
    pesos_rutas = [5,15]
    pesos_ocupacion = [5]        
    pesos_distancia = [5, 2]

    # ========================================================
    # PRODUCTO CARTESIANO
    # ========================================================

    combinaciones = list(

        itertools.product(

            temperaturas,

            factores_enfriamiento,

            iteraciones,

            pesos_coste,

            pesos_rutas,

            pesos_ocupacion,

            pesos_distancia
        )
    )

    # ========================================================
    # DATAFRAME
    # ========================================================

    df_config = pd.DataFrame(

        combinaciones,

        columns=[

            "temperatura_inicial",

            "factor_enfriamiento",

            "iteraciones_por_temperatura",

            "peso_coste",

            "peso_rutas",

            "peso_ocupacion",

            "peso_distancia"
        ]
    )

    # ========================================================
    # TEMPERATURA MÍNIMA
    # ========================================================
    
    df_config["temperatura_minima"] = 1
    

    return df_config

In [11]:
# APLICACIÓN RECOCIDO

df_config = generar_configuraciones_sa()
#df_config_def = df_config.iloc[[0]]
df_config_def = df_config

# display() renderiza la tabla de forma visual y atractiva
display(df_config)

df_experimentos = funciones_recocido.ejecutar_experimentos_sa(df_config_def, solucion_inicial, tareas_recogida_div, matriz_distancias)

# Ordena por mejor coste
df_experimentos.sort_values(by="mejor_coste").head()

,temperatura_inicial,factor_enfriamiento,iteraciones_por_temperatura,peso_coste,peso_rutas,peso_ocupacion,peso_distancia,temperatura_minima
0,100,0.95,75,1,5,5,5,1
1,100,0.95,75,1,5,5,2,1
2,100,0.95,75,1,15,5,5,1
3,100,0.95,75,1,15,5,2,1

==========================================================================================
CONFIGURACIÓN 1 / 4
==========================================================================================
{'temperatura_inicial': 100.0, 'factor_enfriamiento': 0.95, 'iteraciones_por_temperatura': 75.0, 'peso_coste': 1.0, 'peso_rutas': 5.0, 'peso_ocupacion': 5.0, 'peso_distancia': 5.0, 'temperatura_minima': 1.0}
Tiempo de ejecución de configuración: 226.84 s

==========================================================================================
CONFIGURACIÓN 2 / 4
==========================================================================================
{'temperatura_inicial': 100.0, 'factor_enfriamiento': 0.95, 'iteraciones_por_temperatura': 75.0, 'peso_coste': 1.0, 'peso_rutas': 5.0, 'peso_ocupacion': 5.0, 'peso_distancia': 2.0, 'temperatura_minima': 1.0}
Tiempo de ejecución de configuración: 288.35 s

==========================================================================================
CONFIGURACIÓN 3 / 4
==========================================================================================
{'temperatura_inicial': 100.0, 'factor_enfriamiento': 0.95, 'iteraciones_por_temperatura': 75.0, 'peso_coste': 1.0, 'peso_rutas': 15.0, 'peso_ocupacion': 5.0, 'peso_distancia': 5.0, 'temperatura_minima': 1.0}
Tiempo de ejecución de configuración: 227.56 s

==========================================================================================
CONFIGURACIÓN 4 / 4
==========================================================================================
{'temperatura_inicial': 100.0, 'factor_enfriamiento': 0.95, 'iteraciones_por_temperatura': 75.0, 'peso_coste': 1.0, 'peso_rutas': 15.0, 'peso_ocupacion': 5.0, 'peso_distancia': 2.0, 'temperatura_minima': 1.0}
Tiempo de ejecución de configuración: 242.21 s

,temperatura_inicial,factor_enfriamiento,iteraciones_por_temperatura,peso_coste,peso_rutas,peso_ocupacion,peso_distancia,mejor_coste,numero_rutas,ocupacion_media,distancia_total,coste_total,tiempo_total_min,tiempo_ejecucion_s,mejor_solucion,df_resultado,df_historial
1,100.0,0.95,75,1.0,5.0,5.0,2.0,104740.18,26,67.03,831.19,2969.56,1071,288.35,"[{'id': 1, 'centro': 'C-18006728', 'paradas': ...",Metrica Valor 0 ...,ITERACION TEMPERATURA COSTE_ACTUAL ME...
3,100.0,0.95,75,1.0,15.0,5.0,2.0,105015.92,26,68.50,867.67,2967.56,1116,242.21,"[{'id': 1, 'centro': 'C-18006728', 'paradas': ...",Metrica Valor 0 ...,ITERACION TEMPERATURA COSTE_ACTUAL ME...
0,100.0,0.95,75,1.0,5.0,5.0,5.0,107029.70,26,67.16,789.40,2933.60,1057,226.84,"[{'id': 1, 'centro': 'C-18006728', 'paradas': ...",Metrica Valor 0 ...,ITERACION TEMPERATURA COSTE_ACTUAL ME...
2,100.0,0.95,75,1.0,15.0,5.0,5.0,132157.25,27,64.94,782.71,3029.74,1054,227.56,"[{'id': 1, 'centro': 'C-18006728', 'paradas': ...",Metrica Valor 0 ...,ITERACION TEMPERATURA COSTE_ACTUAL ME...

In [14]:
display(df_experimentos.head(20))

# ==========================================================
# EXPORTAR RESULTADOS COMPLETOS A EXCEL MULTIHOJA
# ==========================================================

import pandas as pd

# ==========================================================
# NOMBRE FICHERO
# ==========================================================

nombre_excel = "resultados_experimento_2.xlsx"

# ==========================================================
# CREAR EXCEL
# ==========================================================

with pd.ExcelWriter(
    
    nombre_excel,
    
    engine="openpyxl"
    
) as writer:

    # ======================================================
    # 1. HOJA RESUMEN EXPERIMENTOS
    # ======================================================

    df_resumen = df_experimentos[[
        
        "temperatura_inicial",
        "factor_enfriamiento",
        "iteraciones_por_temperatura",
        
        "peso_coste",
        "peso_rutas",
        "peso_ocupacion",
        "peso_distancia",

        "mejor_coste",
        "numero_rutas",
        "ocupacion_media",
        "distancia_total",
        "coste_total",
        "tiempo_total_min",
        "tiempo_ejecucion_s"

    ]].copy()

    df_resumen = (
        
        df_resumen
        
        .sort_values(
            by="numero_rutas"
        )
        
        .reset_index(drop=True)
    )

    df_resumen.to_excel(
        
        writer,
        
        sheet_name="Resumen",
        
        index=False
    )

    # ======================================================
    # 2. EXPORTAR CADA SOLUCIÓN
    # ======================================================

    for idx, row in df_experimentos.iterrows():

        # --------------------------------------------------
        # NOMBRE HOJA
        # --------------------------------------------------

        nombre_hoja = f"Sol_{idx+1}"

        # --------------------------------------------------
        # DATAFRAME RESULTADO
        # --------------------------------------------------

        df_sol = row["df_resultado"]

        # --------------------------------------------------
        # EXPORTAR
        # --------------------------------------------------

        if isinstance(df_sol, pd.DataFrame):

            df_sol.to_excel(
                
                writer,
                
                sheet_name=nombre_hoja[:31],  # límite Excel
                
                index=False
            )

    # ======================================================
    # 3. EXPORTAR HISTÓRICOS
    # ======================================================

    for idx, row in df_experimentos.iterrows():

        nombre_hoja = f"HIST_{idx+1}"

        df_hist = row["df_historial"]

        if isinstance(df_hist, pd.DataFrame):

            df_hist.to_excel(
                
                writer,
                
                sheet_name=nombre_hoja[:31],
                
                index=False
            )

# ==========================================================
# FIN
# ==========================================================

print(
    f"Excel generado correctamente: {nombre_excel}"
)

,temperatura_inicial,factor_enfriamiento,iteraciones_por_temperatura,peso_coste,peso_rutas,peso_ocupacion,peso_distancia,mejor_coste,numero_rutas,ocupacion_media,distancia_total,coste_total,tiempo_total_min,tiempo_ejecucion_s,mejor_solucion,df_resultado,df_historial
0,100.0,0.95,75,1.0,5.0,5.0,5.0,107029.70,26,67.16,789.40,2933.60,1057,226.84,"[{'id': 1, 'centro': 'C-18006728', 'paradas': ...",Metrica Valor 0 ...,ITERACION TEMPERATURA COSTE_ACTUAL ME...
1,100.0,0.95,75,1.0,5.0,5.0,2.0,104740.18,26,67.03,831.19,2969.56,1071,288.35,"[{'id': 1, 'centro': 'C-18006728', 'paradas': ...",Metrica Valor 0 ...,ITERACION TEMPERATURA COSTE_ACTUAL ME...
2,100.0,0.95,75,1.0,15.0,5.0,5.0,132157.25,27,64.94,782.71,3029.74,1054,227.56,"[{'id': 1, 'centro': 'C-18006728', 'paradas': ...",Metrica Valor 0 ...,ITERACION TEMPERATURA COSTE_ACTUAL ME...
3,100.0,0.95,75,1.0,15.0,5.0,2.0,105015.92,26,68.50,867.67,2967.56,1116,242.21,"[{'id': 1, 'centro': 'C-18006728', 'paradas': ...",Metrica Valor 0 ...,ITERACION TEMPERATURA COSTE_ACTUAL ME...

Excel generado correctamente: resultados_experimento_2.xlsx

In [70]:
# ==========================================================
# EXPORTAR SOLUCIÓN INICIAL A EXCEL MULTIHOJA
# ==========================================================

import pandas as pd

# ==========================================================
# LISTA DETALLE
# ==========================================================

datos_detalle = []

# ==========================================================
# LISTA RESUMEN
# ==========================================================

datos_resumen = []

# ==========================================================
# RECORRER RUTAS
# ==========================================================

for ruta in solucion_inicial:

    # ------------------------------------------------------
    # DATOS GENERALES RUTA
    # ------------------------------------------------------

    ruta_id = ruta["id"]

    centro = ruta["centro"]

    alumnos_ruta = ruta["alumnos"]

    bus = ruta["bus"]

    ocupacion = ruta["ocupacion"]

    tiempo = ruta["tiempo"]

    distancia = ruta["distancia"]

    coste = ruta["coste"]

    num_paradas = len(
        ruta["paradas"]
    )

    # ======================================================
    # RESUMEN
    # ======================================================

    datos_resumen.append({

        "RUTA": ruta_id,

        "CENTRO": centro,

        "NUM_PARADAS": num_paradas,

        "ALUMNOS_RUTA": alumnos_ruta,

        "BUS": bus,

        "OCUPACION_%": ocupacion,

        "TIEMPO_MIN": tiempo,

        "DISTANCIA_KM": distancia,

        "COSTE_€": coste
    })

    # ======================================================
    # DETALLE PARADAS
    # ======================================================

    for orden, parada in enumerate(

        ruta["paradas"],

        start=1
    ):

        datos_detalle.append({

            "RUTA": ruta_id,

            "CENTRO": centro,

            "ORDEN": orden,

            "PARADA": parada["parada"],

            "ALUMNOS_PARADA": parada["alumnos"],

            "ALUMNOS_RUTA": alumnos_ruta,

            "BUS": bus,

            "OCUPACION_%": ocupacion,

            "TIEMPO_MIN": tiempo,

            "DISTANCIA_KM": distancia,

            "COSTE_€": coste
        })

# ==========================================================
# DATAFRAMES
# ==========================================================

df_resumen = pd.DataFrame(
    datos_resumen
)

df_detalle = pd.DataFrame(
    datos_detalle
)

# ==========================================================
# EXPORTAR EXCEL MULTIHOJA
# ==========================================================

nombre_fichero = "solucion_inicial.xlsx"

with pd.ExcelWriter(

    nombre_fichero,

    engine="openpyxl"

) as writer:

    # ------------------------------------------------------
    # HOJA RESUMEN
    # ------------------------------------------------------

    df_resumen.to_excel(

        writer,

        sheet_name="Resumen_Rutas",

        index=False
    )

    # ------------------------------------------------------
    # HOJA DETALLE
    # ------------------------------------------------------

    df_detalle.to_excel(

        writer,

        sheet_name="Detalle_Rutas",

        index=False
    )

# ==========================================================
# MENSAJE
# ==========================================================

print(
    f"Excel exportado correctamente: {nombre_fichero}"
)

Excel exportado correctamente: solucion_inicial.xlsx

In [16]:
import importlib
importlib.reload(funciones_recocido)

print("--- EJECUTANDO RECOCIDO SIMULADO ---")
mejor_sol_sa_j, df_res_sa_j, df_hist_sa_j = funciones_recocido.recocido_simulado(
    solucion_inicial=solucion_inicial,
    tareas_recogida=tareas_recogida_div,  # <--- CAMBIA AQUÍ: Usa el DataFrame original (ej. df_tareas_recogida)
    matriz_distancias=matriz_distancias,
    temperatura_inicial=100,
    temperatura_minima=1,
    factor_enfriamiento=0.95,
    iteraciones_por_temperatura=125,
    peso_coste=0.5,
    peso_rutas=10,
    peso_ocupacion=0.5,
    peso_distancia=0.5,
    mostrar_logs=True
)

# Unificar o limpiar los valores NaN en la tabla comparativa
df_comparativo.loc[df_comparativo["Metrica"] == "Total alumnos", "Algoritmo Genético"] = 836.00

# O de forma general, cambiar los NaN restantes por un guion para que quede elegante
df_comparativo = df_comparativo.fillna("-")
df_experimentos.sort_values(by="mejor_coste").iloc[0]

# ============================================================
# CONSTRUCCIÓN DEL CUADRO COMPARATIVO UNIENDO DATASET
# ============================================================
df_res_sa.columns = ["Metrica", "Recocido Simulado"]
df_res_ga.columns = ["Metrica", "Algoritmo Genético"]

df_comparativo = pd.merge(df_res_sa, df_res_ga, on="Metrica", how="outer")
print("\n========================================================")
print("               TABLA COMPARATIVA DE MÉTODOS")
print("========================================================")
print(df_comparativo)

--- EJECUTANDO RECOCIDO SIMULADO ---
T=95.00 | Mejor coste=18097.83
T=90.25 | Mejor coste=17504.95
T=85.74 | Mejor coste=17504.95
T=81.45 | Mejor coste=17504.95
T=77.38 | Mejor coste=14936.04
T=73.51 | Mejor coste=14923.98
T=69.83 | Mejor coste=14870.25
T=66.34 | Mejor coste=14870.25
T=63.02 | Mejor coste=14870.25
T=59.87 | Mejor coste=14870.25
T=56.88 | Mejor coste=14870.25
T=54.04 | Mejor coste=14870.25
T=51.33 | Mejor coste=14870.25
T=48.77 | Mejor coste=14870.25
T=46.33 | Mejor coste=14870.25
T=44.01 | Mejor coste=14870.25
T=41.81 | Mejor coste=14870.25
T=39.72 | Mejor coste=14870.25
T=37.74 | Mejor coste=14870.25
T=35.85 | Mejor coste=14870.25
T=34.06 | Mejor coste=14870.25
T=32.35 | Mejor coste=14870.25
T=30.74 | Mejor coste=14870.25
T=29.20 | Mejor coste=14869.14
T=27.74 | Mejor coste=14869.14
T=26.35 | Mejor coste=14869.14
T=25.03 | Mejor coste=14869.14
T=23.78 | Mejor coste=14866.20
T=22.59 | Mejor coste=14866.20
T=21.46 | Mejor coste=14866.20
T=20.39 | Mejor coste=14866.20
T=19.37 | Mejor coste=14866.20
T=18.40 | Mejor coste=14866.20
T=17.48 | Mejor coste=14866.20
T=16.61 | Mejor coste=14866.20
T=15.78 | Mejor coste=14866.20
T=14.99 | Mejor coste=14866.20
T=14.24 | Mejor coste=14866.20
T=13.53 | Mejor coste=14866.20
T=12.85 | Mejor coste=14866.20
T=12.21 | Mejor coste=14866.20
T=11.60 | Mejor coste=14866.20
T=11.02 | Mejor coste=14866.20
T=10.47 | Mejor coste=14866.20
T=9.94 | Mejor coste=14866.20
T=9.45 | Mejor coste=14858.77
T=8.97 | Mejor coste=14850.12
T=8.53 | Mejor coste=14850.12
T=8.10 | Mejor coste=14834.87
T=7.69 | Mejor coste=14816.60
T=7.31 | Mejor coste=14802.42
T=6.94 | Mejor coste=14793.24
T=6.60 | Mejor coste=14786.71
T=6.27 | Mejor coste=14786.71
T=5.95 | Mejor coste=14782.79
T=5.66 | Mejor coste=14767.68
T=5.37 | Mejor coste=14767.68
T=5.10 | Mejor coste=14767.68
T=4.85 | Mejor coste=14767.68
T=4.61 | Mejor coste=14767.68
T=4.38 | Mejor coste=14758.78
T=4.16 | Mejor coste=14747.45
T=3.95 | Mejor coste=14732.10
T=3.75 | Mejor coste=14732.10
T=3.56 | Mejor coste=14732.10
T=3.39 | Mejor coste=14732.10
T=3.22 | Mejor coste=14732.10
T=3.06 | Mejor coste=14732.10
T=2.90 | Mejor coste=14732.10
T=2.76 | Mejor coste=14732.10
T=2.62 | Mejor coste=14724.37
T=2.49 | Mejor coste=14713.78
T=2.36 | Mejor coste=14713.78
T=2.25 | Mejor coste=14713.78
T=2.13 | Mejor coste=14713.78
T=2.03 | Mejor coste=14713.00
T=1.93 | Mejor coste=14708.11
T=1.83 | Mejor coste=14703.91
T=1.74 | Mejor coste=14703.91
T=1.65 | Mejor coste=14703.91
T=1.57 | Mejor coste=14703.91
T=1.49 | Mejor coste=14703.91
T=1.42 | Mejor coste=14701.98
T=1.35 | Mejor coste=14700.78
T=1.28 | Mejor coste=14699.67
T=1.21 | Mejor coste=14696.58
T=1.15 | Mejor coste=14695.71
T=1.10 | Mejor coste=12159.56
T=1.04 | Mejor coste=12159.56
T=0.99 | Mejor coste=12159.45

In [19]:
print("\n--- EJECUTANDO ALGORITMO GENÉTICO ---")
mejor_sol_ga, df_res_ga, df_hist_ga = funciones_recocido.algoritmo_genetico(
    solucion_inicial=solucion_inicial,
    tareas_recogida=tareas_recogida_div,  # <--- CAMBIA AQUÍ: Usa el DataFrame original (ej. df_tareas_recogida)
    matriz_distancias=matriz_distancias,
    tamano_poblacion=30,
    generaciones=50,
    probabilidad_mutacion=0.2,
    peso_coste=1.0,
    peso_rutas=5.0,
    peso_ocupacion=5.0,
    peso_distancia=5.0,
    mostrar_logs=True
)

--- EJECUTANDO ALGORITMO GENÉTICO ---
Gen 1/50 | Mejor Coste: 200111.83 | Coste Medio: 218507.15
Gen 2/50 | Mejor Coste: 200111.83 | Coste Medio: 91962.21
Gen 3/50 | Mejor Coste: 189605.11 | Coste Medio: 42303.59
Gen 4/50 | Mejor Coste: 189605.11 | Coste Medio: 42125.16
Gen 5/50 | Mejor Coste: 189605.11 | Coste Medio: 41641.41
Gen 6/50 | Mejor Coste: 189605.11 | Coste Medio: 55637.27
Gen 7/50 | Mejor Coste: 189605.11 | Coste Medio: 19969.87
Gen 8/50 | Mejor Coste: 189605.11 | Coste Medio: 6320.17
Gen 9/50 | Mejor Coste: 189605.11 | Coste Medio: 6320.17
Gen 10/50 | Mejor Coste: 189605.11 | Coste Medio: 6320.17
Gen 11/50 | Mejor Coste: 189605.11 | Coste Medio: 6320.17
Gen 12/50 | Mejor Coste: 189605.11 | Coste Medio: 6320.17
Gen 13/50 | Mejor Coste: 189605.11 | Coste Medio: 6320.17
Gen 14/50 | Mejor Coste: 189605.11 | Coste Medio: 6320.17
Gen 15/50 | Mejor Coste: 189577.61 | Coste Medio: 12639.42
Gen 16/50 | Mejor Coste: 189577.61 | Coste Medio: 12639.03
Gen 17/50 | Mejor Coste: 189577.61 | Coste Medio: 25278.05
Gen 18/50 | Mejor Coste: 189577.61 | Coste Medio: 37918.76
Gen 19/50 | Mejor Coste: 189577.61 | Coste Medio: 18957.76
Gen 20/50 | Mejor Coste: 189577.61 | Coste Medio: 6319.25
Gen 21/50 | Mejor Coste: 189577.61 | Coste Medio: 18957.76
Gen 22/50 | Mejor Coste: 189577.61 | Coste Medio: 31599.99
Gen 23/50 | Mejor Coste: 189577.61 | Coste Medio: 37919.25
Gen 24/50 | Mejor Coste: 189577.61 | Coste Medio: 31603.72
Gen 25/50 | Mejor Coste: 189577.61 | Coste Medio: 37924.45
Gen 26/50 | Mejor Coste: 189577.61 | Coste Medio: 25280.74
Gen 27/50 | Mejor Coste: 189549.87 | Coste Medio: 25451.16
Gen 28/50 | Mejor Coste: 189549.87 | Coste Medio: 38263.82
Gen 29/50 | Mejor Coste: 189549.87 | Coste Medio: 18955.91
Gen 30/50 | Mejor Coste: 189549.87 | Coste Medio: 12636.66
Gen 31/50 | Mejor Coste: 189549.87 | Coste Medio: 6318.33
Gen 32/50 | Mejor Coste: 189546.87 | Coste Medio: 12636.56
Gen 33/50 | Mejor Coste: 189546.87 | Coste Medio: 12636.56
Gen 34/50 | Mejor Coste: 189546.87 | Coste Medio: 18961.95
Gen 35/50 | Mejor Coste: 189546.87 | Coste Medio: 25272.92
Gen 36/50 | Mejor Coste: 189542.47 | Coste Medio: 18954.54
Gen 37/50 | Mejor Coste: 189542.47 | Coste Medio: 25272.62
Gen 38/50 | Mejor Coste: 189542.47 | Coste Medio: 31590.71
Gen 39/50 | Mejor Coste: 189542.47 | Coste Medio: 18954.25
Gen 40/50 | Mejor Coste: 189542.47 | Coste Medio: 18954.25
Gen 41/50 | Mejor Coste: 189542.47 | Coste Medio: 6318.08
Gen 42/50 | Mejor Coste: 189542.47 | Coste Medio: 6318.08
Gen 43/50 | Mejor Coste: 189542.47 | Coste Medio: 18954.25
Gen 44/50 | Mejor Coste: 189542.47 | Coste Medio: 12636.16
Gen 45/50 | Mejor Coste: 189542.47 | Coste Medio: 12636.16
Gen 46/50 | Mejor Coste: 189542.47 | Coste Medio: 12636.16
Gen 47/50 | Mejor Coste: 189542.47 | Coste Medio: 18954.25
Gen 48/50 | Mejor Coste: 189542.47 | Coste Medio: 25272.33
Gen 49/50 | Mejor Coste: 189542.47 | Coste Medio: 18954.25
Gen 50/50 | Mejor Coste: 189542.47 | Coste Medio: 12636.16

In [86]:
# ============================================================
# EJECUCIÓN COMPARATIVA CORREGIDA: SA vs GA
# ============================================================

import importlib
importlib.reload(funciones_recocido)

print("--- EJECUTANDO RECOCIDO SIMULADO ---")
mejor_sol_sa, df_res_sa, df_hist_sa = funciones_recocido.recocido_simulado(
    solucion_inicial=solucion_inicial,
    tareas_recogida=tareas_recogida_div,  # <--- CAMBIA AQUÍ: Usa el DataFrame original (ej. df_tareas_recogida)
    matriz_distancias=matriz_distancias,
    temperatura_inicial=100,
    temperatura_minima=1,
    factor_enfriamiento=0.95,
    iteraciones_por_temperatura=75,
    peso_coste=1.0,
    peso_rutas=5.0,
    peso_ocupacion=5.0,
    peso_distancia=5.0,
    mostrar_logs=True
)

print("\n--- EJECUTANDO ALGORITMO GENÉTICO ---")
mejor_sol_ga, df_res_ga, df_hist_ga = funciones_recocido.algoritmo_genetico(
    solucion_inicial=solucion_inicial,
    tareas_recogida=tareas_recogida_div,  # <--- CAMBIA AQUÍ: Usa el DataFrame original (ej. df_tareas_recogida)
    matriz_distancias=matriz_distancias,
    tamano_poblacion=30,
    generaciones=50,
    probabilidad_mutacion=0.2,
    peso_coste=1.0,
    peso_rutas=5.0,
    peso_ocupacion=5.0,
    peso_distancia=5.0,
    mostrar_logs=True
)

--- EJECUTANDO RECOCIDO SIMULADO ---
T=95.00 | Mejor coste=184545.04
T=90.25 | Mejor coste=184306.44
T=85.74 | Mejor coste=159030.30
T=81.45 | Mejor coste=158937.78
T=77.38 | Mejor coste=158898.73
T=73.51 | Mejor coste=158706.80
T=69.83 | Mejor coste=158623.48
T=66.34 | Mejor coste=158623.48
T=63.02 | Mejor coste=158623.48
T=59.87 | Mejor coste=133491.75
T=56.88 | Mejor coste=133491.75
T=54.04 | Mejor coste=133491.75
T=51.33 | Mejor coste=133491.75
T=48.77 | Mejor coste=133465.82
T=46.33 | Mejor coste=133465.82
T=44.01 | Mejor coste=133349.60
T=41.81 | Mejor coste=133349.60
T=39.72 | Mejor coste=133349.60
T=37.74 | Mejor coste=133015.76
T=35.85 | Mejor coste=133015.76
T=34.06 | Mejor coste=122611.98
T=32.35 | Mejor coste=114522.73
T=30.74 | Mejor coste=113074.58
T=29.20 | Mejor coste=107739.44
T=27.74 | Mejor coste=107705.07
T=26.35 | Mejor coste=107495.05
T=25.03 | Mejor coste=107495.05
T=23.78 | Mejor coste=107495.05
T=22.59 | Mejor coste=107495.05
T=21.46 | Mejor coste=107495.05
T=20.39 | Mejor coste=107495.05
T=19.37 | Mejor coste=107495.05
T=18.40 | Mejor coste=107495.05
T=17.48 | Mejor coste=107495.05
T=16.61 | Mejor coste=107495.05
T=15.78 | Mejor coste=107495.05
T=14.99 | Mejor coste=107368.98
T=14.24 | Mejor coste=107363.04
T=13.53 | Mejor coste=107363.04
T=12.85 | Mejor coste=107328.85
T=12.21 | Mejor coste=107253.75
T=11.60 | Mejor coste=107222.98
T=11.02 | Mejor coste=107189.53
T=10.47 | Mejor coste=107148.25
T=9.94 | Mejor coste=107146.00
T=9.45 | Mejor coste=107146.00
T=8.97 | Mejor coste=107129.28
T=8.53 | Mejor coste=107129.28
T=8.10 | Mejor coste=107129.28
T=7.69 | Mejor coste=107113.25
T=7.31 | Mejor coste=107096.20
T=6.94 | Mejor coste=107092.30
T=6.60 | Mejor coste=107092.30
T=6.27 | Mejor coste=107092.30
T=5.95 | Mejor coste=107092.30
T=5.66 | Mejor coste=107092.30
T=5.37 | Mejor coste=107092.30
T=5.10 | Mejor coste=107092.30
T=4.85 | Mejor coste=107089.35
T=4.61 | Mejor coste=107089.35
T=4.38 | Mejor coste=107089.35
T=4.16 | Mejor coste=107089.35
T=3.95 | Mejor coste=107089.35
T=3.75 | Mejor coste=107089.35
T=3.56 | Mejor coste=107089.35
T=3.39 | Mejor coste=107089.35
T=3.22 | Mejor coste=107089.35
T=3.06 | Mejor coste=107084.80
T=2.90 | Mejor coste=107076.85
T=2.76 | Mejor coste=107076.85
T=2.62 | Mejor coste=107076.85
T=2.49 | Mejor coste=107076.85
T=2.36 | Mejor coste=107076.85
T=2.25 | Mejor coste=107076.85
T=2.13 | Mejor coste=107076.85
T=2.03 | Mejor coste=107076.85
T=1.93 | Mejor coste=107076.85
T=1.83 | Mejor coste=107076.85
T=1.74 | Mejor coste=107076.85
T=1.65 | Mejor coste=107076.85
T=1.57 | Mejor coste=107076.85
T=1.49 | Mejor coste=107061.30
T=1.42 | Mejor coste=107061.30
T=1.35 | Mejor coste=107061.30
T=1.28 | Mejor coste=107061.30
T=1.21 | Mejor coste=107061.30
T=1.15 | Mejor coste=107061.30
T=1.10 | Mejor coste=107061.30
T=1.04 | Mejor coste=107061.30
T=0.99 | Mejor coste=107061.30

--- EJECUTANDO ALGORITMO GENÉTICO ---
Gen 1/50 | Mejor Coste: 200111.83 | Coste Medio: 219592.36
Gen 2/50 | Mejor Coste: 200111.83 | Coste Medio: 34012.06
Gen 3/50 | Mejor Coste: 200111.83 | Coste Medio: 26681.58
Gen 4/50 | Mejor Coste: 200111.83 | Coste Medio: 13340.79
Gen 5/50 | Mejor Coste: 200111.83 | Coste Medio: 6670.39
Gen 6/50 | Mejor Coste: 200111.83 | Coste Medio: 20011.18
Gen 7/50 | Mejor Coste: 200111.83 | Coste Medio: 6670.39
Gen 8/50 | Mejor Coste: 200111.83 | Coste Medio: 6670.39
Gen 9/50 | Mejor Coste: 200097.68 | Coste Medio: 20010.71
Gen 10/50 | Mejor Coste: 200097.68 | Coste Medio: 13339.85
Gen 11/50 | Mejor Coste: 200097.68 | Coste Medio: 13341.27
Gen 12/50 | Mejor Coste: 200097.68 | Coste Medio: 13339.85
Gen 13/50 | Mejor Coste: 200097.68 | Coste Medio: 20009.77
Gen 14/50 | Mejor Coste: 200097.68 | Coste Medio: 20092.77
Gen 15/50 | Mejor Coste: 200097.68 | Coste Medio: 6669.92
Gen 16/50 | Mejor Coste: 200097.68 | Coste Medio: 6669.92
Gen 17/50 | Mejor Coste: 200097.68 | Coste Medio: 13339.85
Gen 18/50 | Mejor Coste: 200097.68 | Coste Medio: 20016.72
Gen 19/50 | Mejor Coste: 200097.68 | Coste Medio: 13346.80
Gen 20/50 | Mejor Coste: 200097.68 | Coste Medio: 6669.92
Gen 21/50 | Mejor Coste: 200097.68 | Coste Medio: 6669.92
Gen 22/50 | Mejor Coste: 200097.68 | Coste Medio: 13339.85
Gen 23/50 | Mejor Coste: 200097.68 | Coste Medio: 6669.92
Gen 24/50 | Mejor Coste: 200097.68 | Coste Medio: 6669.92
Gen 25/50 | Mejor Coste: 200097.68 | Coste Medio: 6669.92
Gen 26/50 | Mejor Coste: 200097.68 | Coste Medio: 6669.92
Gen 27/50 | Mejor Coste: 200097.68 | Coste Medio: 6669.92
Gen 28/50 | Mejor Coste: 200097.68 | Coste Medio: 20009.77
Gen 29/50 | Mejor Coste: 200097.68 | Coste Medio: 13339.85
Gen 30/50 | Mejor Coste: 200097.68 | Coste Medio: 33349.61
Gen 31/50 | Mejor Coste: 200097.68 | Coste Medio: 40021.01
Gen 32/50 | Mejor Coste: 200097.68 | Coste Medio: 26681.16
Gen 33/50 | Mejor Coste: 200097.68 | Coste Medio: 26679.69
Gen 34/50 | Mejor Coste: 200097.68 | Coste Medio: 26679.91
Gen 35/50 | Mejor Coste: 200097.68 | Coste Medio: 13340.07
Gen 36/50 | Mejor Coste: 200097.68 | Coste Medio: 20010.21
Gen 37/50 | Mejor Coste: 200097.68 | Coste Medio: 33350.06
Gen 38/50 | Mejor Coste: 200097.68 | Coste Medio: 13339.85
Gen 39/50 | Mejor Coste: 200097.68 | Coste Medio: 26679.69
Gen 40/50 | Mejor Coste: 200097.68 | Coste Medio: 26679.69
Gen 41/50 | Mejor Coste: 200097.68 | Coste Medio: 26679.69
Gen 42/50 | Mejor Coste: 200097.68 | Coste Medio: 13339.85
Gen 43/50 | Mejor Coste: 200097.68 | Coste Medio: 13339.85
Gen 44/50 | Mejor Coste: 200097.68 | Coste Medio: 20009.77
Gen 45/50 | Mejor Coste: 200097.68 | Coste Medio: 20009.77
Gen 46/50 | Mejor Coste: 200097.68 | Coste Medio: 26679.69
Gen 47/50 | Mejor Coste: 200097.68 | Coste Medio: 33349.61
Gen 48/50 | Mejor Coste: 200097.68 | Coste Medio: 20009.77
Gen 49/50 | Mejor Coste: 200097.68 | Coste Medio: 33349.61
Gen 50/50 | Mejor Coste: 200097.68 | Coste Medio: 6669.92
                    Metrica Recocido Simulado Algoritmo Genético
0                 Algoritmo                 -           Genético
1               Coste total           3370.72            3518.92
2           Distancia total            904.92            1133.56
3       Factor enfriamiento              0.95                  -
4              Generaciones                 -                 50
5   Iteraciones temperatura              75.0                  -
6               Mejor coste         185499.14          219866.72
7              Numero rutas              30.0                 30
8           Ocupacion media             57.61              54.73
9                Peso coste               1.0                  -
10           Peso distancia               5.0                  -
11           Peso ocupacion               5.0                  -
12               Peso rutas               5.0                  -
13                Poblacion                 -                 30
14      Temperatura inicial             100.0                  -
15       Temperatura minima               1.0                  -
16     Tiempo ejecucion (s)            126.55              65.15
17            Total alumnos             836.0              836.0

========================================================
               TABLA COMPARATIVA DE MÉTODOS
========================================================
                    Metrica  Recocido Simulado Algoritmo Genético
0                 Algoritmo                NaN           Genético
1               Coste total            2933.60            3458.74
2           Distancia total             800.37            1150.91
3       Factor enfriamiento               0.95                NaN
4              Generaciones                NaN                 50
5   Iteraciones temperatura              75.00                NaN
6               Mejor coste          107061.30          200097.68
7              Numero rutas              26.00                 29
8           Ocupacion media              67.19              56.51
9                Peso coste               1.00                NaN
10           Peso distancia               5.00                NaN
11           Peso ocupacion               5.00                NaN
12               Peso rutas               5.00                NaN
13                Poblacion                NaN                 30
14      Temperatura inicial             100.00                NaN
15       Temperatura minima               1.00                NaN
16     Tiempo ejecucion (s)             206.97               31.5
17            Total alumnos             836.00                NaN

In [97]:
print("\n--- OTRAS EJECUCIONES ALGORITMO GENÉTICO ---")

mejor_sol_ga_2, df_res_ga_2, df_hist_ga_2 = funciones_recocido.algoritmo_genetico(
    solucion_inicial=solucion_inicial,
    tareas_recogida=tareas_recogida_div,  # <--- CAMBIA AQUÍ: Usa el DataFrame original (ej. df_tareas_recogida)
    matriz_distancias=matriz_distancias,
    tamano_poblacion=30,
    generaciones=20,
    probabilidad_mutacion=0.01,
    peso_coste=1.0,
    peso_rutas=5.0,
    peso_ocupacion=5.0,
    peso_distancia=5.0,
    mostrar_logs=True
)

mejor_sol_ga_3, df_res_ga_3, df_hist_ga_3 = funciones_recocido.algoritmo_genetico(
    solucion_inicial=solucion_inicial,
    tareas_recogida=tareas_recogida_div,  # <--- CAMBIA AQUÍ: Usa el DataFrame original (ej. df_tareas_recogida)
    matriz_distancias=matriz_distancias,
    tamano_poblacion=50,
    generaciones=50,
    probabilidad_mutacion=0.01,
    peso_coste=1.0,
    peso_rutas=5.0,
    peso_ocupacion=5.0,
    peso_distancia=5.0,
    mostrar_logs=True
)

mejor_sol_ga_4, df_res_ga_4, df_hist_ga_4 = funciones_recocido.algoritmo_genetico(
    solucion_inicial=solucion_inicial,
    tareas_recogida=tareas_recogida_div,  # <--- CAMBIA AQUÍ: Usa el DataFrame original (ej. df_tareas_recogida)
    matriz_distancias=matriz_distancias,
    tamano_poblacion=100,
    generaciones=50,
    probabilidad_mutacion=0.01,
    peso_coste=1.0,
    peso_rutas=5.0,
    peso_ocupacion=5.0,
    peso_distancia=5.0,
    mostrar_logs=True
)


mejor_sol_ga_5, df_res_ga_5, df_hist_ga_5 = funciones_recocido.algoritmo_genetico(
    solucion_inicial=solucion_inicial,
    tareas_recogida=tareas_recogida_div,  # <--- CAMBIA AQUÍ: Usa el DataFrame original (ej. df_tareas_recogida)
    matriz_distancias=matriz_distancias,
    tamano_poblacion=200,
    generaciones=10,
    probabilidad_mutacion=0.01,
    peso_coste=6.0,
    peso_rutas=5.0,
    peso_ocupacion=5.0,
    peso_distancia=5.0,
    mostrar_logs=True
)

--- OTRAS EJECUCIONES ALGORITMO GENÉTICO ---
Gen 1/20 | Mejor Coste: 200111.83 | Coste Medio: 218534.62
Gen 2/20 | Mejor Coste: 200111.83 | Coste Medio: 78617.42
Gen 3/20 | Mejor Coste: 200111.83 | Coste Medio: 57984.91
Gen 4/20 | Mejor Coste: 200111.83 | Coste Medio: 21331.40
Gen 5/20 | Mejor Coste: 200111.83 | Coste Medio: 20671.29
Gen 6/20 | Mejor Coste: 200111.83 | Coste Medio: 26681.58
Gen 7/20 | Mejor Coste: 200111.83 | Coste Medio: 26681.58
Gen 8/20 | Mejor Coste: 200111.83 | Coste Medio: 6670.39
Gen 9/20 | Mejor Coste: 200111.83 | Coste Medio: 6670.39
Gen 10/20 | Mejor Coste: 200111.83 | Coste Medio: 13340.79
Gen 11/20 | Mejor Coste: 200111.83 | Coste Medio: 6670.39
Gen 12/20 | Mejor Coste: 200111.83 | Coste Medio: 20011.18
Gen 13/20 | Mejor Coste: 200111.83 | Coste Medio: 26681.58
Gen 14/20 | Mejor Coste: 200111.83 | Coste Medio: 26681.58
Gen 15/20 | Mejor Coste: 200111.83 | Coste Medio: 40022.37
Gen 16/20 | Mejor Coste: 200111.83 | Coste Medio: 6670.39
Gen 17/20 | Mejor Coste: 200111.83 | Coste Medio: 6670.39
Gen 18/20 | Mejor Coste: 200111.83 | Coste Medio: 6670.39
Gen 19/20 | Mejor Coste: 200111.83 | Coste Medio: 13340.79
Gen 20/20 | Mejor Coste: 200111.83 | Coste Medio: 6670.39
Gen 1/50 | Mejor Coste: 200111.83 | Coste Medio: 219022.97
Gen 2/50 | Mejor Coste: 200111.83 | Coste Medio: 47463.56
Gen 3/50 | Mejor Coste: 200111.83 | Coste Medio: 29998.65
Gen 4/50 | Mejor Coste: 200111.83 | Coste Medio: 16802.49
Gen 5/50 | Mejor Coste: 200111.83 | Coste Medio: 8004.47
Gen 6/50 | Mejor Coste: 200111.83 | Coste Medio: 12006.71
Gen 7/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 8/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 9/50 | Mejor Coste: 200111.83 | Coste Medio: 8004.47
Gen 10/50 | Mejor Coste: 200111.83 | Coste Medio: 12006.71
Gen 11/50 | Mejor Coste: 200111.83 | Coste Medio: 12006.71
Gen 12/50 | Mejor Coste: 200111.83 | Coste Medio: 16008.95
Gen 13/50 | Mejor Coste: 200111.83 | Coste Medio: 12006.71
Gen 14/50 | Mejor Coste: 200111.83 | Coste Medio: 16008.95
Gen 15/50 | Mejor Coste: 200111.83 | Coste Medio: 12006.71
Gen 16/50 | Mejor Coste: 200111.83 | Coste Medio: 8004.47
Gen 17/50 | Mejor Coste: 200111.83 | Coste Medio: 8004.47
Gen 18/50 | Mejor Coste: 200111.83 | Coste Medio: 8004.47
Gen 19/50 | Mejor Coste: 200111.83 | Coste Medio: 16008.95
Gen 20/50 | Mejor Coste: 200111.83 | Coste Medio: 16008.95
Gen 21/50 | Mejor Coste: 200111.83 | Coste Medio: 12006.71
Gen 22/50 | Mejor Coste: 200111.83 | Coste Medio: 16008.95
Gen 23/50 | Mejor Coste: 200111.83 | Coste Medio: 12006.71
Gen 24/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 25/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 26/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 27/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 28/50 | Mejor Coste: 200111.83 | Coste Medio: 8004.47
Gen 29/50 | Mejor Coste: 200111.83 | Coste Medio: 8004.47
Gen 30/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 31/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 32/50 | Mejor Coste: 200111.83 | Coste Medio: 8004.47
Gen 33/50 | Mejor Coste: 200111.83 | Coste Medio: 12006.71
Gen 34/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 35/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 36/50 | Mejor Coste: 200111.83 | Coste Medio: 8004.47
Gen 37/50 | Mejor Coste: 200111.83 | Coste Medio: 12006.71
Gen 38/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 39/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 40/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 41/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 42/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 43/50 | Mejor Coste: 200111.83 | Coste Medio: 8004.47
Gen 44/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 45/50 | Mejor Coste: 200111.83 | Coste Medio: 8004.47
Gen 46/50 | Mejor Coste: 200072.43 | Coste Medio: 20010.40
Gen 47/50 | Mejor Coste: 200072.43 | Coste Medio: 16007.37
Gen 48/50 | Mejor Coste: 200072.43 | Coste Medio: 12005.13
Gen 49/50 | Mejor Coste: 200072.43 | Coste Medio: 12005.13
Gen 50/50 | Mejor Coste: 200072.43 | Coste Medio: 4001.45
Gen 1/50 | Mejor Coste: 200111.83 | Coste Medio: 219104.46
Gen 2/50 | Mejor Coste: 200111.83 | Coste Medio: 32459.28
Gen 3/50 | Mejor Coste: 200111.83 | Coste Medio: 12799.29
Gen 4/50 | Mejor Coste: 200111.83 | Coste Medio: 4200.18
Gen 5/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 6/50 | Mejor Coste: 200111.83 | Coste Medio: 6003.35
Gen 7/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 8/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 9/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 10/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 11/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 12/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 13/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 14/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 15/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 16/50 | Mejor Coste: 200111.83 | Coste Medio: 6003.35
Gen 17/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 18/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 19/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 20/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 21/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 22/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 23/50 | Mejor Coste: 200111.83 | Coste Medio: 6003.35
Gen 24/50 | Mejor Coste: 200111.83 | Coste Medio: 6003.35
Gen 25/50 | Mejor Coste: 200111.83 | Coste Medio: 6003.35
Gen 26/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 27/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 28/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 29/50 | Mejor Coste: 200111.83 | Coste Medio: 8004.47
Gen 30/50 | Mejor Coste: 200111.83 | Coste Medio: 6003.35
Gen 31/50 | Mejor Coste: 200111.83 | Coste Medio: 6003.35
Gen 32/50 | Mejor Coste: 200111.83 | Coste Medio: 6003.35
Gen 33/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 34/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 35/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 36/50 | Mejor Coste: 200111.83 | Coste Medio: 6003.35
Gen 37/50 | Mejor Coste: 200111.83 | Coste Medio: 6003.35
Gen 38/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 39/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 40/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 41/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 42/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 43/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 44/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 45/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 46/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 47/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 48/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 49/50 | Mejor Coste: 200111.83 | Coste Medio: 2001.12
Gen 50/50 | Mejor Coste: 200111.83 | Coste Medio: 4002.24
Gen 1/10 | Mejor Coste: 217225.73 | Coste Medio: 237198.98
Gen 2/10 | Mejor Coste: 217225.73 | Coste Medio: 48273.62
Gen 3/10 | Mejor Coste: 217225.73 | Coste Medio: 31536.31
Gen 4/10 | Mejor Coste: 217225.73 | Coste Medio: 26825.32
Gen 5/10 | Mejor Coste: 217225.73 | Coste Medio: 13802.83
Gen 6/10 | Mejor Coste: 217225.73 | Coste Medio: 11401.72
Gen 7/10 | Mejor Coste: 217225.73 | Coste Medio: 8959.79
Gen 8/10 | Mejor Coste: 217225.73 | Coste Medio: 5498.56
Gen 9/10 | Mejor Coste: 217225.73 | Coste Medio: 6665.65
Gen 10/10 | Mejor Coste: 217225.73 | Coste Medio: 6678.68
Gen 1/250 | Mejor Coste: 197097.40 | Coste Medio: 216230.21
Gen 2/250 | Mejor Coste: 197097.40 | Coste Medio: 42727.92
Gen 3/250 | Mejor Coste: 197097.40 | Coste Medio: 13063.71
Gen 4/250 | Mejor Coste: 197097.40 | Coste Medio: 10352.19
Gen 5/250 | Mejor Coste: 197095.06 | Coste Medio: 7391.12
Gen 6/250 | Mejor Coste: 197095.06 | Coste Medio: 9855.53
Gen 7/250 | Mejor Coste: 197095.06 | Coste Medio: 14785.03
Gen 8/250 | Mejor Coste: 197095.06 | Coste Medio: 2463.69
Gen 9/250 | Mejor Coste: 197095.06 | Coste Medio: 2463.69
Gen 10/250 | Mejor Coste: 197004.08 | Coste Medio: 4926.24
Gen 11/250 | Mejor Coste: 197004.08 | Coste Medio: 7387.65
Gen 12/250 | Mejor Coste: 197004.08 | Coste Medio: 4925.10
Gen 13/250 | Mejor Coste: 186438.72 | Coste Medio: 7255.59
Gen 14/250 | Mejor Coste: 186438.72 | Coste Medio: 4660.97
Gen 15/250 | Mejor Coste: 186438.72 | Coste Medio: 6991.45
Gen 16/250 | Mejor Coste: 186438.72 | Coste Medio: 4727.13
Gen 17/250 | Mejor Coste: 186438.72 | Coste Medio: 4660.97
Gen 18/250 | Mejor Coste: 186415.18 | Coste Medio: 6991.16
Gen 19/250 | Mejor Coste: 186415.18 | Coste Medio: 6990.74
Gen 20/250 | Mejor Coste: 186415.18 | Coste Medio: 6990.83
Gen 21/250 | Mejor Coste: 186415.18 | Coste Medio: 6990.75
Gen 22/250 | Mejor Coste: 186415.18 | Coste Medio: 9320.94
Gen 23/250 | Mejor Coste: 186415.18 | Coste Medio: 2330.19
Gen 24/250 | Mejor Coste: 186415.18 | Coste Medio: 2330.19
Gen 25/250 | Mejor Coste: 186415.18 | Coste Medio: 2330.19
Gen 26/250 | Mejor Coste: 186415.18 | Coste Medio: 6990.57
Gen 27/250 | Mejor Coste: 186415.18 | Coste Medio: 6990.93
Gen 28/250 | Mejor Coste: 186415.18 | Coste Medio: 4660.38
Gen 29/250 | Mejor Coste: 186410.40 | Coste Medio: 16312.92
Gen 30/250 | Mejor Coste: 186410.40 | Coste Medio: 9386.80
Gen 31/250 | Mejor Coste: 186410.40 | Coste Medio: 6990.51
Gen 32/250 | Mejor Coste: 186410.40 | Coste Medio: 6990.51
Gen 33/250 | Mejor Coste: 186410.40 | Coste Medio: 2330.13
Gen 34/250 | Mejor Coste: 186410.40 | Coste Medio: 4661.35
Gen 35/250 | Mejor Coste: 186410.40 | Coste Medio: 9325.04
Gen 36/250 | Mejor Coste: 186410.40 | Coste Medio: 4660.26
Gen 37/250 | Mejor Coste: 186410.40 | Coste Medio: 4660.26
Gen 38/250 | Mejor Coste: 186410.40 | Coste Medio: 6990.39
Gen 39/250 | Mejor Coste: 186410.40 | Coste Medio: 2330.13
Gen 40/250 | Mejor Coste: 186410.40 | Coste Medio: 4660.26
Gen 41/250 | Mejor Coste: 186410.40 | Coste Medio: 9320.52
Gen 42/250 | Mejor Coste: 186410.40 | Coste Medio: 4660.26
Gen 43/250 | Mejor Coste: 186410.40 | Coste Medio: 4660.26
Gen 44/250 | Mejor Coste: 186410.40 | Coste Medio: 4660.26
Gen 45/250 | Mejor Coste: 186410.40 | Coste Medio: 2330.13
Gen 46/250 | Mejor Coste: 186410.40 | Coste Medio: 2330.13
Gen 47/250 | Mejor Coste: 186410.40 | Coste Medio: 4660.26
Gen 48/250 | Mejor Coste: 186410.40 | Coste Medio: 4660.26
Gen 49/250 | Mejor Coste: 186410.40 | Coste Medio: 6990.42
Gen 50/250 | Mejor Coste: 186410.40 | Coste Medio: 4660.26
Gen 51/250 | Mejor Coste: 186410.40 | Coste Medio: 9320.69
Gen 52/250 | Mejor Coste: 186410.40 | Coste Medio: 11651.53
Gen 53/250 | Mejor Coste: 186410.40 | Coste Medio: 9321.11
Gen 54/250 | Mejor Coste: 186410.40 | Coste Medio: 4660.58
Gen 55/250 | Mejor Coste: 186410.40 | Coste Medio: 2330.13
Gen 56/250 | Mejor Coste: 186369.62 | Coste Medio: 4659.75
Gen 57/250 | Mejor Coste: 186369.62 | Coste Medio: 2329.62
Gen 58/250 | Mejor Coste: 186369.62 | Coste Medio: 2329.62
Gen 59/250 | Mejor Coste: 186369.62 | Coste Medio: 2329.62
Gen 60/250 | Mejor Coste: 186369.62 | Coste Medio: 2329.62
Gen 61/250 | Mejor Coste: 186369.62 | Coste Medio: 2329.62
Gen 62/250 | Mejor Coste: 186369.62 | Coste Medio: 6988.86
Gen 63/250 | Mejor Coste: 186369.62 | Coste Medio: 6989.64
Gen 64/250 | Mejor Coste: 186369.62 | Coste Medio: 4659.24
Gen 65/250 | Mejor Coste: 186369.62 | Coste Medio: 4659.24
Gen 66/250 | Mejor Coste: 186369.62 | Coste Medio: 2329.62
Gen 67/250 | Mejor Coste: 186369.62 | Coste Medio: 2329.62
Gen 68/250 | Mejor Coste: 186369.62 | Coste Medio: 2329.62
Gen 69/250 | Mejor Coste: 186369.62 | Coste Medio: 4659.24
Gen 70/250 | Mejor Coste: 186369.62 | Coste Medio: 2329.62
Gen 71/250 | Mejor Coste: 186369.62 | Coste Medio: 2329.62
Gen 72/250 | Mejor Coste: 186369.62 | Coste Medio: 6988.86
Gen 73/250 | Mejor Coste: 186369.62 | Coste Medio: 4659.24
Gen 74/250 | Mejor Coste: 186369.62 | Coste Medio: 6988.86
Gen 75/250 | Mejor Coste: 186369.62 | Coste Medio: 11648.10
Gen 76/250 | Mejor Coste: 186369.62 | Coste Medio: 18637.09
Gen 77/250 | Mejor Coste: 186369.62 | Coste Medio: 11649.36
Gen 78/250 | Mejor Coste: 186367.48 | Coste Medio: 6988.83
Gen 79/250 | Mejor Coste: 186367.48 | Coste Medio: 16307.21
Gen 80/250 | Mejor Coste: 186367.48 | Coste Medio: 9318.37
Gen 81/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 82/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 83/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 84/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 85/250 | Mejor Coste: 186367.48 | Coste Medio: 9318.37
Gen 86/250 | Mejor Coste: 186367.48 | Coste Medio: 6988.78
Gen 87/250 | Mejor Coste: 186367.48 | Coste Medio: 6988.78
Gen 88/250 | Mejor Coste: 186367.48 | Coste Medio: 6988.78
Gen 89/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 90/250 | Mejor Coste: 186367.48 | Coste Medio: 6988.87
Gen 91/250 | Mejor Coste: 186367.48 | Coste Medio: 9318.56
Gen 92/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.28
Gen 93/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 94/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 95/250 | Mejor Coste: 186367.48 | Coste Medio: 11648.22
Gen 96/250 | Mejor Coste: 186367.48 | Coste Medio: 6989.65
Gen 97/250 | Mejor Coste: 186367.48 | Coste Medio: 11648.96
Gen 98/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 99/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 100/250 | Mejor Coste: 186367.48 | Coste Medio: 6988.78
Gen 101/250 | Mejor Coste: 186367.48 | Coste Medio: 6988.78
Gen 102/250 | Mejor Coste: 186367.48 | Coste Medio: 6988.78
Gen 103/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 104/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 105/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 106/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 107/250 | Mejor Coste: 186367.48 | Coste Medio: 4660.45
Gen 108/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 109/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 110/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 111/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 112/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 113/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 114/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 115/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.41
Gen 116/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 117/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 118/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 119/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 120/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 121/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 122/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 123/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 124/250 | Mejor Coste: 186367.48 | Coste Medio: 6988.78
Gen 125/250 | Mejor Coste: 186367.48 | Coste Medio: 6988.78
Gen 126/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 127/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 128/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 129/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 130/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 131/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 132/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 133/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 134/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 135/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 136/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 137/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 138/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 139/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 140/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 141/250 | Mejor Coste: 186367.48 | Coste Medio: 4660.08
Gen 142/250 | Mejor Coste: 186367.48 | Coste Medio: 9321.06
Gen 143/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.47
Gen 144/250 | Mejor Coste: 186367.48 | Coste Medio: 6989.06
Gen 145/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 146/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 147/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.51
Gen 148/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 149/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 150/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 151/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 152/250 | Mejor Coste: 186367.48 | Coste Medio: 6988.78
Gen 153/250 | Mejor Coste: 186367.48 | Coste Medio: 6988.78
Gen 154/250 | Mejor Coste: 186367.48 | Coste Medio: 6988.78
Gen 155/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 156/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 157/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 158/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 159/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 160/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 161/250 | Mejor Coste: 186367.48 | Coste Medio: 2329.59
Gen 162/250 | Mejor Coste: 186367.48 | Coste Medio: 4659.19
Gen 163/250 | Mejor Coste: 186347.08 | Coste Medio: 9318.12
Gen 164/250 | Mejor Coste: 186347.08 | Coste Medio: 9318.14
Gen 165/250 | Mejor Coste: 186347.08 | Coste Medio: 7087.50
Gen 166/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 167/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 168/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 169/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 170/250 | Mejor Coste: 186347.08 | Coste Medio: 4658.68
Gen 171/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 172/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 173/250 | Mejor Coste: 186347.08 | Coste Medio: 4658.68
Gen 174/250 | Mejor Coste: 186347.08 | Coste Medio: 4658.68
Gen 175/250 | Mejor Coste: 186347.08 | Coste Medio: 6988.51
Gen 176/250 | Mejor Coste: 186347.08 | Coste Medio: 4659.21
Gen 177/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 178/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 179/250 | Mejor Coste: 186347.08 | Coste Medio: 4658.68
Gen 180/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 181/250 | Mejor Coste: 186347.08 | Coste Medio: 4658.96
Gen 182/250 | Mejor Coste: 186347.08 | Coste Medio: 6988.48
Gen 183/250 | Mejor Coste: 186347.08 | Coste Medio: 4658.68
Gen 184/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 185/250 | Mejor Coste: 186347.08 | Coste Medio: 4658.68
Gen 186/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 187/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 188/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 189/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 190/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 191/250 | Mejor Coste: 186347.08 | Coste Medio: 4658.68
Gen 192/250 | Mejor Coste: 186347.08 | Coste Medio: 9317.35
Gen 193/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 194/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 195/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 196/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 197/250 | Mejor Coste: 186347.08 | Coste Medio: 6988.44
Gen 198/250 | Mejor Coste: 186347.08 | Coste Medio: 4659.10
Gen 199/250 | Mejor Coste: 186347.08 | Coste Medio: 4659.10
Gen 200/250 | Mejor Coste: 186347.08 | Coste Medio: 4658.98
Gen 201/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 202/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 203/250 | Mejor Coste: 186347.08 | Coste Medio: 2329.34
Gen 204/250 | Mejor Coste: 186337.64 | Coste Medio: 4658.56
Gen 205/250 | Mejor Coste: 186337.64 | Coste Medio: 9317.74
Gen 206/250 | Mejor Coste: 186337.64 | Coste Medio: 4658.84
Gen 207/250 | Mejor Coste: 186337.64 | Coste Medio: 4658.84
Gen 208/250 | Mejor Coste: 186337.64 | Coste Medio: 9317.69

In [104]:
mejor_sol_ga_6, df_res_ga_6, df_hist_ga_6 = funciones_recocido.algoritmo_genetico(
    solucion_inicial=solucion_inicial,
    tareas_recogida=tareas_recogida_div,
    matriz_distancias=matriz_distancias,
    tamano_poblacion=850,             # Más individuos para garantizar diversidad inicial
    generaciones=250,                # Suficientes ciclos para permitir la convergencia
    probabilidad_mutacion=0.20,      # Exploración activa para mover paradas entre rutas
    peso_coste=1.0,
    peso_rutas=20.0,                 # Presión extrema para forzar la reducción de autobuses
    peso_ocupacion=5.0,
    peso_distancia=2.0,              # Permitimos que aumenten temporalmente los km si eso ahorra una ruta
    mostrar_logs=True
)

Gen 1/250 | Mejor Coste: 197097.40 | Coste Medio: 216667.43
Gen 2/250 | Mejor Coste: 191902.06 | Coste Medio: 47458.61
Gen 3/250 | Mejor Coste: 191897.16 | Coste Medio: 26227.08
Gen 4/250 | Mejor Coste: 191897.16 | Coste Medio: 12497.87
Gen 5/250 | Mejor Coste: 191897.16 | Coste Medio: 7149.29
Gen 6/250 | Mejor Coste: 191897.16 | Coste Medio: 4207.43
Gen 7/250 | Mejor Coste: 191897.16 | Coste Medio: 4691.78
Gen 8/250 | Mejor Coste: 191897.16 | Coste Medio: 2712.93
Gen 9/250 | Mejor Coste: 191897.16 | Coste Medio: 2166.74
Gen 10/250 | Mejor Coste: 191897.16 | Coste Medio: 1158.29
Gen 11/250 | Mejor Coste: 191897.16 | Coste Medio: 1187.76
Gen 12/250 | Mejor Coste: 191897.16 | Coste Medio: 225.76
Gen 13/250 | Mejor Coste: 191897.16 | Coste Medio: 451.52
Gen 14/250 | Mejor Coste: 191897.16 | Coste Medio: 451.52
Gen 15/250 | Mejor Coste: 191897.16 | Coste Medio: 451.52
Gen 16/250 | Mejor Coste: 191897.16 | Coste Medio: 677.28
Gen 17/250 | Mejor Coste: 191896.40 | Coste Medio: 1128.81
Gen 18/250 | Mejor Coste: 191896.40 | Coste Medio: 677.28
Gen 19/250 | Mejor Coste: 191896.40 | Coste Medio: 1128.80
Gen 20/250 | Mejor Coste: 191896.40 | Coste Medio: 1128.82
Gen 21/250 | Mejor Coste: 191896.40 | Coste Medio: 1354.57
Gen 22/250 | Mejor Coste: 191896.40 | Coste Medio: 1128.81
Gen 23/250 | Mejor Coste: 191896.40 | Coste Medio: 677.28
Gen 24/250 | Mejor Coste: 191896.40 | Coste Medio: 1128.80
Gen 25/250 | Mejor Coste: 191896.40 | Coste Medio: 451.52
Gen 26/250 | Mejor Coste: 191896.40 | Coste Medio: 225.76
Gen 27/250 | Mejor Coste: 191896.40 | Coste Medio: 225.76
Gen 28/250 | Mejor Coste: 191896.40 | Coste Medio: 677.28
Gen 29/250 | Mejor Coste: 181331.04 | Coste Medio: 1116.37
Gen 30/250 | Mejor Coste: 181331.04 | Coste Medio: 1544.60
Gen 31/250 | Mejor Coste: 181329.78 | Coste Medio: 1292.40
Gen 32/250 | Mejor Coste: 181329.78 | Coste Medio: 1279.98
Gen 33/250 | Mejor Coste: 181329.78 | Coste Medio: 1279.98
Gen 34/250 | Mejor Coste: 181329.78 | Coste Medio: 864.16
Gen 35/250 | Mejor Coste: 181329.78 | Coste Medio: 643.02
Gen 36/250 | Mejor Coste: 181329.78 | Coste Medio: 639.99
Gen 37/250 | Mejor Coste: 181329.78 | Coste Medio: 426.66
Gen 38/250 | Mejor Coste: 181329.78 | Coste Medio: 639.99
Gen 39/250 | Mejor Coste: 181329.78 | Coste Medio: 426.66
Gen 40/250 | Mejor Coste: 181329.78 | Coste Medio: 640.04
Gen 41/250 | Mejor Coste: 181329.78 | Coste Medio: 853.32
Gen 42/250 | Mejor Coste: 181329.78 | Coste Medio: 426.66
Gen 43/250 | Mejor Coste: 181271.98 | Coste Medio: 639.92
Gen 44/250 | Mejor Coste: 181271.98 | Coste Medio: 426.52
Gen 45/250 | Mejor Coste: 181271.98 | Coste Medio: 426.52
Gen 46/250 | Mejor Coste: 181271.98 | Coste Medio: 642.90
Gen 47/250 | Mejor Coste: 181271.98 | Coste Medio: 639.78
Gen 48/250 | Mejor Coste: 181271.98 | Coste Medio: 1066.31
Gen 49/250 | Mejor Coste: 181271.98 | Coste Medio: 1066.31
Gen 50/250 | Mejor Coste: 181271.98 | Coste Medio: 426.52
Gen 51/250 | Mejor Coste: 181265.82 | Coste Medio: 639.78
Gen 52/250 | Mejor Coste: 181265.82 | Coste Medio: 639.77
Gen 53/250 | Mejor Coste: 181265.82 | Coste Medio: 213.25
Gen 54/250 | Mejor Coste: 181265.82 | Coste Medio: 213.25
Gen 55/250 | Mejor Coste: 181265.82 | Coste Medio: 426.51
Gen 56/250 | Mejor Coste: 181265.82 | Coste Medio: 213.25
Gen 57/250 | Mejor Coste: 181265.82 | Coste Medio: 213.25
Gen 58/250 | Mejor Coste: 181265.82 | Coste Medio: 213.25
Gen 59/250 | Mejor Coste: 181265.82 | Coste Medio: 213.25
Gen 60/250 | Mejor Coste: 181265.82 | Coste Medio: 213.25
Gen 61/250 | Mejor Coste: 181265.82 | Coste Medio: 426.51
Gen 62/250 | Mejor Coste: 181243.32 | Coste Medio: 853.00
Gen 63/250 | Mejor Coste: 181243.32 | Coste Medio: 639.68
Gen 64/250 | Mejor Coste: 181243.32 | Coste Medio: 639.68
Gen 65/250 | Mejor Coste: 181238.66 | Coste Medio: 426.45
Gen 66/250 | Mejor Coste: 181238.66 | Coste Medio: 639.68
Gen 67/250 | Mejor Coste: 181238.66 | Coste Medio: 213.22
Gen 68/250 | Mejor Coste: 181238.66 | Coste Medio: 213.22
Gen 69/250 | Mejor Coste: 181238.66 | Coste Medio: 853.04
Gen 70/250 | Mejor Coste: 181230.86 | Coste Medio: 639.80
Gen 71/250 | Mejor Coste: 181230.86 | Coste Medio: 426.43
Gen 72/250 | Mejor Coste: 181230.86 | Coste Medio: 213.21
Gen 73/250 | Mejor Coste: 181230.86 | Coste Medio: 213.21
Gen 74/250 | Mejor Coste: 181230.86 | Coste Medio: 426.43
Gen 75/250 | Mejor Coste: 181230.86 | Coste Medio: 639.64
Gen 76/250 | Mejor Coste: 181211.50 | Coste Medio: 639.62
Gen 77/250 | Mejor Coste: 181211.50 | Coste Medio: 426.40
Gen 78/250 | Mejor Coste: 181211.50 | Coste Medio: 213.19
Gen 79/250 | Mejor Coste: 181172.54 | Coste Medio: 852.77
Gen 80/250 | Mejor Coste: 181172.54 | Coste Medio: 1065.92
Gen 81/250 | Mejor Coste: 181172.54 | Coste Medio: 426.29
Gen 82/250 | Mejor Coste: 181172.54 | Coste Medio: 852.59
Gen 83/250 | Mejor Coste: 181172.54 | Coste Medio: 1492.04
Gen 84/250 | Mejor Coste: 181172.54 | Coste Medio: 1065.74
Gen 85/250 | Mejor Coste: 181172.54 | Coste Medio: 852.59
Gen 86/250 | Mejor Coste: 181172.54 | Coste Medio: 855.68
Gen 87/250 | Mejor Coste: 181172.54 | Coste Medio: 426.29
Gen 88/250 | Mejor Coste: 181158.18 | Coste Medio: 639.50
Gen 89/250 | Mejor Coste: 181158.18 | Coste Medio: 426.35
Gen 90/250 | Mejor Coste: 181158.18 | Coste Medio: 213.13
Gen 91/250 | Mejor Coste: 181158.18 | Coste Medio: 213.13
Gen 92/250 | Mejor Coste: 181158.18 | Coste Medio: 426.25
Gen 93/250 | Mejor Coste: 181158.18 | Coste Medio: 213.13
Gen 94/250 | Mejor Coste: 181158.18 | Coste Medio: 213.13
Gen 95/250 | Mejor Coste: 181158.18 | Coste Medio: 639.38
Gen 96/250 | Mejor Coste: 181158.18 | Coste Medio: 639.38
Gen 97/250 | Mejor Coste: 181158.18 | Coste Medio: 213.13
Gen 98/250 | Mejor Coste: 181140.76 | Coste Medio: 426.23
Gen 99/250 | Mejor Coste: 181140.76 | Coste Medio: 639.34
Gen 100/250 | Mejor Coste: 181140.76 | Coste Medio: 1065.55
Gen 101/250 | Mejor Coste: 181140.76 | Coste Medio: 426.21
Gen 102/250 | Mejor Coste: 181140.76 | Coste Medio: 639.32
Gen 103/250 | Mejor Coste: 181140.76 | Coste Medio: 426.21
Gen 104/250 | Mejor Coste: 181140.76 | Coste Medio: 639.32
Gen 105/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 106/250 | Mejor Coste: 181140.76 | Coste Medio: 426.21
Gen 107/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 108/250 | Mejor Coste: 181140.76 | Coste Medio: 426.23
Gen 109/250 | Mejor Coste: 181140.76 | Coste Medio: 639.36
Gen 110/250 | Mejor Coste: 181140.76 | Coste Medio: 426.21
Gen 111/250 | Mejor Coste: 181140.76 | Coste Medio: 639.32
Gen 112/250 | Mejor Coste: 181140.76 | Coste Medio: 852.43
Gen 113/250 | Mejor Coste: 181140.76 | Coste Medio: 1278.70
Gen 114/250 | Mejor Coste: 181140.76 | Coste Medio: 852.48
Gen 115/250 | Mejor Coste: 181140.76 | Coste Medio: 639.43
Gen 116/250 | Mejor Coste: 181140.76 | Coste Medio: 426.21
Gen 117/250 | Mejor Coste: 181140.76 | Coste Medio: 426.21
Gen 118/250 | Mejor Coste: 181140.76 | Coste Medio: 426.21
Gen 119/250 | Mejor Coste: 181140.76 | Coste Medio: 426.21
Gen 120/250 | Mejor Coste: 181140.76 | Coste Medio: 639.32
Gen 121/250 | Mejor Coste: 181140.76 | Coste Medio: 639.32
Gen 122/250 | Mejor Coste: 181140.76 | Coste Medio: 639.32
Gen 123/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 124/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 125/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 126/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 127/250 | Mejor Coste: 181140.76 | Coste Medio: 426.21
Gen 128/250 | Mejor Coste: 181140.76 | Coste Medio: 426.36
Gen 129/250 | Mejor Coste: 181140.76 | Coste Medio: 426.36
Gen 130/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 131/250 | Mejor Coste: 181140.76 | Coste Medio: 426.21
Gen 132/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 133/250 | Mejor Coste: 181140.76 | Coste Medio: 426.26
Gen 134/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 135/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 136/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 137/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 138/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 139/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 140/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 141/250 | Mejor Coste: 181140.76 | Coste Medio: 213.11
Gen 142/250 | Mejor Coste: 181140.76 | Coste Medio: 426.21
Gen 143/250 | Mejor Coste: 181140.76 | Coste Medio: 1278.66
Gen 144/250 | Mejor Coste: 181140.76 | Coste Medio: 852.43
Gen 145/250 | Mejor Coste: 181129.76 | Coste Medio: 639.31
Gen 146/250 | Mejor Coste: 181129.76 | Coste Medio: 639.31
Gen 147/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 148/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 149/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 150/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 151/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 152/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 153/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 154/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 155/250 | Mejor Coste: 181129.76 | Coste Medio: 426.19
Gen 156/250 | Mejor Coste: 181129.76 | Coste Medio: 639.28
Gen 157/250 | Mejor Coste: 181129.76 | Coste Medio: 852.38
Gen 158/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 159/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 160/250 | Mejor Coste: 181129.76 | Coste Medio: 1065.47
Gen 161/250 | Mejor Coste: 181129.76 | Coste Medio: 639.28
Gen 162/250 | Mejor Coste: 181129.76 | Coste Medio: 1278.62
Gen 163/250 | Mejor Coste: 181129.76 | Coste Medio: 1491.67
Gen 164/250 | Mejor Coste: 181129.76 | Coste Medio: 1065.47
Gen 165/250 | Mejor Coste: 181129.76 | Coste Medio: 852.41
Gen 166/250 | Mejor Coste: 181129.76 | Coste Medio: 1065.50
Gen 167/250 | Mejor Coste: 181129.76 | Coste Medio: 852.45
Gen 168/250 | Mejor Coste: 181129.76 | Coste Medio: 852.45
Gen 169/250 | Mejor Coste: 181129.76 | Coste Medio: 639.32
Gen 170/250 | Mejor Coste: 181129.76 | Coste Medio: 426.19
Gen 171/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 172/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 173/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 174/250 | Mejor Coste: 181129.76 | Coste Medio: 213.09
Gen 179/250 | Mejor Coste: 181129.76 | Coste Medio: 2131.21
Gen 180/250 | Mejor Coste: 181129.76 | Coste Medio: 1065.61
Gen 181/250 | Mejor Coste: 181118.26 | Coste Medio: 1491.78
Gen 182/250 | Mejor Coste: 181118.26 | Coste Medio: 1065.58
Gen 183/250 | Mejor Coste: 181118.26 | Coste Medio: 1278.83
Gen 184/250 | Mejor Coste: 181118.26 | Coste Medio: 1491.87
Gen 185/250 | Mejor Coste: 181118.26 | Coste Medio: 1704.94
Gen 186/250 | Mejor Coste: 181118.26 | Coste Medio: 1076.44
Gen 187/250 | Mejor Coste: 181118.26 | Coste Medio: 213.08
Gen 188/250 | Mejor Coste: 181118.26 | Coste Medio: 213.08
Gen 189/250 | Mejor Coste: 181118.26 | Coste Medio: 426.16
Gen 190/250 | Mejor Coste: 181118.26 | Coste Medio: 639.24
Gen 191/250 | Mejor Coste: 181118.26 | Coste Medio: 852.32
Gen 192/250 | Mejor Coste: 181118.26 | Coste Medio: 1065.42
Gen 193/250 | Mejor Coste: 181118.26 | Coste Medio: 1065.46
Gen 194/250 | Mejor Coste: 181118.26 | Coste Medio: 1065.49
Gen 195/250 | Mejor Coste: 181118.26 | Coste Medio: 1065.49
Gen 196/250 | Mejor Coste: 181118.26 | Coste Medio: 852.32
Gen 197/250 | Mejor Coste: 181118.26 | Coste Medio: 426.16
Gen 198/250 | Mejor Coste: 181118.26 | Coste Medio: 213.08
Gen 199/250 | Mejor Coste: 181118.26 | Coste Medio: 426.16
Gen 200/250 | Mejor Coste: 181118.26 | Coste Medio: 639.30
Gen 201/250 | Mejor Coste: 181118.26 | Coste Medio: 639.30
Gen 202/250 | Mejor Coste: 181118.26 | Coste Medio: 639.46
Gen 203/250 | Mejor Coste: 181118.26 | Coste Medio: 852.63
Gen 204/250 | Mejor Coste: 181118.26 | Coste Medio: 426.32
Gen 205/250 | Mejor Coste: 181118.26 | Coste Medio: 213.08
Gen 206/250 | Mejor Coste: 181118.26 | Coste Medio: 426.16
Gen 207/250 | Mejor Coste: 181118.26 | Coste Medio: 426.16
Gen 208/250 | Mejor Coste: 181118.26 | Coste Medio: 639.29
Gen 209/250 | Mejor Coste: 181118.26 | Coste Medio: 639.29
Gen 210/250 | Mejor Coste: 181118.26 | Coste Medio: 852.37
Gen 211/250 | Mejor Coste: 181118.26 | Coste Medio: 426.16
Gen 212/250 | Mejor Coste: 181118.26 | Coste Medio: 213.08
Gen 213/250 | Mejor Coste: 181118.26 | Coste Medio: 426.16
Gen 214/250 | Mejor Coste: 181118.26 | Coste Medio: 639.24
Gen 215/250 | Mejor Coste: 181116.66 | Coste Medio: 639.38
Gen 216/250 | Mejor Coste: 181116.66 | Coste Medio: 426.30
Gen 217/250 | Mejor Coste: 181116.66 | Coste Medio: 426.16
Gen 218/250 | Mejor Coste: 181116.66 | Coste Medio: 213.08
Gen 219/250 | Mejor Coste: 181116.66 | Coste Medio: 426.16
Gen 220/250 | Mejor Coste: 181116.66 | Coste Medio: 426.16
Gen 221/250 | Mejor Coste: 181116.66 | Coste Medio: 426.16
Gen 222/250 | Mejor Coste: 181116.66 | Coste Medio: 426.16
Gen 223/250 | Mejor Coste: 181116.66 | Coste Medio: 426.16
Gen 224/250 | Mejor Coste: 181116.66 | Coste Medio: 852.31
Gen 225/250 | Mejor Coste: 181116.66 | Coste Medio: 639.24
Gen 226/250 | Mejor Coste: 181116.66 | Coste Medio: 426.16
Gen 227/250 | Mejor Coste: 181116.66 | Coste Medio: 213.08
Gen 228/250 | Mejor Coste: 181116.66 | Coste Medio: 639.24
Gen 229/250 | Mejor Coste: 181116.66 | Coste Medio: 639.24
Gen 230/250 | Mejor Coste: 181116.66 | Coste Medio: 426.16
Gen 231/250 | Mejor Coste: 181116.66 | Coste Medio: 213.08
Gen 232/250 | Mejor Coste: 181116.66 | Coste Medio: 213.08
Gen 233/250 | Mejor Coste: 181116.66 | Coste Medio: 213.08
Gen 234/250 | Mejor Coste: 181112.00 | Coste Medio: 639.23
Gen 235/250 | Mejor Coste: 181112.00 | Coste Medio: 852.31
Gen 236/250 | Mejor Coste: 181112.00 | Coste Medio: 852.32
Gen 237/250 | Mejor Coste: 181112.00 | Coste Medio: 639.22
Gen 238/250 | Mejor Coste: 181112.00 | Coste Medio: 213.07
Gen 239/250 | Mejor Coste: 181112.00 | Coste Medio: 426.15
Gen 240/250 | Mejor Coste: 181045.52 | Coste Medio: 852.21
Gen 241/250 | Mejor Coste: 181045.52 | Coste Medio: 639.14
Gen 242/250 | Mejor Coste: 181045.52 | Coste Medio: 212.99
Gen 243/250 | Mejor Coste: 181045.52 | Coste Medio: 425.99
Gen 244/250 | Mejor Coste: 181045.52 | Coste Medio: 638.98
Gen 245/250 | Mejor Coste: 181045.52 | Coste Medio: 852.12
Gen 246/250 | Mejor Coste: 181045.52 | Coste Medio: 426.05
Gen 247/250 | Mejor Coste: 181045.52 | Coste Medio: 425.99
Gen 248/250 | Mejor Coste: 181045.52 | Coste Medio: 851.98
Gen 249/250 | Mejor Coste: 181045.52 | Coste Medio: 425.99
Gen 250/250 | Mejor Coste: 181045.52 | Coste Medio: 212.99

In [23]:
import pandas as pd
import matplotlib.pyplot as plt

# =====================================================================
# 1. GENERACIÓN DE LA TABLA COMPARATIVA DE PARAMETRIZACIONES
# =====================================================================

def extraer_metricas_ga(df_res, nombre_config):
    """
    Transpone el DataFrame de resultados de cada ejecución para 
    convertir las métricas en filas y las configuraciones en columnas.
    """
    # Copia el DataFrame y asegura que la columna 'Metrica' sea el índice
    df = df_res.copy()
    if 'Metrica' in df.columns:
        df = df.set_index('Metrica')
    
    # Renombrar la columna de valor al nombre de la configuración evaluada
    if 'Valor' in df.columns:
        df = df.rename(columns={'Valor': nombre_config})
    elif 'Algoritmo Genético' in df.columns:
        df = df.rename(columns={'Algoritmo Genético': nombre_config})
    
    return df

# Procesar los 5 DataFrames individuales
df_c1 = extraer_metricas_ga(df_res_ga,   "Configuración 1\n(Pob:30, Gen:50, Pm:0.20)")
"""df_c2 = extraer_metricas_ga(df_res_ga_2, "Configuración 2\n(Pob:30, Gen:20, Pm:0.01)")
df_c3 = extraer_metricas_ga(df_res_ga_3, "Configuración 3\n(Pob:50, Gen:50, Pm:0.01)")
df_c4 = extraer_metricas_ga(df_res_ga_4, "Configuración 4\n(Pob:100, Gen:50, Pm:0.01)")
df_c5 = extraer_metricas_ga(df_res_ga_5, "Configuración 5\n(Pob:200, Gen:10, Pm:0.01)")
df_c6 = extraer_metricas_ga(df_res_ga_6, "Configuración 6\n(Pob:800, Gen:250, Pm:0.01)")
"""

# Consolidar todas las columnas mediante un join por el índice de métricas
tabla_comparativa_ga = df_c1.join([df_c2, df_c3, df_c4, df_c5, df_c6], how='outer')

# Limpieza estética: Rellenar nulos de parámetros ausentes con un guión
tabla_comparativa_ga = tabla_comparativa_ga.fillna("-")

print("=======================================================================================")
print("             TABLA DE DESARROLLO EXPERIMENTAL: PARAMETRIZACIONES DEL GA")
print("=======================================================================================")
display(tabla_comparativa_ga)



# =====================================================================
# 3. EXPORTACIÓN DE LA TABLA COMPARATIVA A EXCEL
# =====================================================================

# Creamos una copia para no alterar la visualización en el Notebook
tabla_excel = tabla_comparativa_ga.copy()

# Opcional: Reemplazar los saltos de línea (\n) de los nombres de las columnas 
# por un espacio para que los encabezados queden limpios en Excel
tabla_excel.columns = [col.replace('\n', ' ') for col in tabla_excel.columns]

# Definir el nombre del archivo de salida
nombre_archivo_excel = "Desarrollo_Experimental_GA.xlsx"

# Exportar a Excel (incluyendo el índice, ya que ahí están los nombres de las métricas)
with pd.ExcelWriter(nombre_archivo_excel, engine='openpyxl') as writer:
    tabla_excel.to_excel(writer, sheet_name='Comparativa_GA')
    
    # Autoajuste automático del ancho de las columnas en el archivo de salida
    worksheet = writer.sheets['Comparativa_GA']
    for col in worksheet.columns:
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = col[0].column_letter
        worksheet.column_dimensions[col_letter].width = max(max_len + 3, 12)

print(f"\n[OK] Tabla exportada correctamente al archivo: '{nombre_archivo_excel}'")

NameError: name 'df_c2' is not defined

In [22]:
# Unificar o limpiar los valores NaN en la tabla comparativa
df_comparativo.loc[df_comparativo["Metrica"] == "Total alumnos", "Algoritmo Genético"] = 836.00

# O de forma general, cambiar los NaN restantes por un guion para que quede elegante
df_comparativo = df_comparativo.fillna("-")
df_experimentos.sort_values(by="mejor_coste").iloc[0]

# ============================================================
# CONSTRUCCIÓN DEL CUADRO COMPARATIVO UNIENDO DATASET
# ============================================================
df_res_sa.columns = ["Metrica", "Recocido Simulado"]
df_res_ga.columns = ["Metrica", "Algoritmo Genético"]

df_comparativo = pd.merge(df_res_sa, df_res_ga, on="Metrica", how="outer")
print("\n========================================================")
print("               TABLA COMPARATIVA DE MÉTODOS")
print("========================================================")
print(df_comparativo)



tabla_excel_c1 = df_comparativo.copy()

# Opcional: Reemplazar los saltos de línea (\n) de los nombres de las columnas 
# por un espacio para que los encabezados queden limpios en Excel
tabla_excel_c1.columns = [col.replace('\n', ' ') for col in tabla_excel_c1.columns]

# Definir el nombre del archivo de salida
nombre_archivo_excel = "Compara_Recocido_GA.xlsx"

# Exportar a Excel (incluyendo el índice, ya que ahí están los nombres de las métricas)
with pd.ExcelWriter(nombre_archivo_excel, engine='openpyxl') as writer:
    tabla_excel_c1.to_excel(writer, sheet_name='Comparativa_Recocido_GA')
    
    # Autoajuste automático del ancho de las columnas en el archivo de salida
    worksheet = writer.sheets['Comparativa_Recocido_GA']
    for col in worksheet.columns:
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = col[0].column_letter
        worksheet.column_dimensions[col_letter].width = max(max_len + 3, 12)

print(f"\n[OK] Tabla exportada correctamente al archivo: '{nombre_archivo_excel}'")

NameError: name 'df_comparativo' is not defined